apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: flux-system
spec:
  replicas: 1  # Number of Nginx instances
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  #